---
ansible_host: 192.168.0.196

ansible_connection: ssh
#ansible_user: client

hostname: Client1
ansible_sudo_pass: "{{ vault_SUDO_PASSWORD }}"

TIMEZONE: "Asia/Yekaterinburg"

#For role minio
disks_for_minio:
  - { disk: '/dev/sdb', partition: '/dev/sdb1', mount_pint: '/mnt/disk1'}
  - { disk: '/dev/sdc', partition: '/dev/sdc1', mount_pint: '/mnt/disk2'}
...
