---
SSH_PORT_for_sshd_conf: 2022

docker_username: docker
docker_username_upassword: 1qaZ15795321

removeble_app:
  - "cloud-init"

removeble_folders:
  - "/etc/cloud/"
  - "/var/lib/cloud/"

instaleble_packages:
  - "mc"
  - "curl"
  - "tree"
  - "bash-completion"
  - "wget"

allow_tcp_ports:
  - 22
  - 2022

etcd_version: v3.4.17
etcd_token: sthxidhv9vyxQ34cBrDQeYcS6x
kubeVersion: 1.22.2
CIDR: 10.43.0.0/16
calico_version: 3.20.2
...