---
# handlers file for prepare_os

- import_tasks: Restart_services.yml

- import_tasks: Remove_folders.yml



- name: Reboot initiated by Ansible
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
  become: yes
