---
- name: Set up multiple authorized keys
  ansible.posix.authorized_key:
    user: root
    state: present
    key: '{{ lookup("file", item) }}'
  with_fileglob:
    - public_keys/*.pub
  become: true
...