---
- name: Install HAproxy
  apt:
    name: haproxy
    state: present
    update_cache: yes
  when: inventory_hostname in groups['kuber_master']

- name: Create systemd service for etcd
  when: inventory_hostname in groups['kuber_master']  
  template:
    src: haproxy.cfg.j2
    dest: "/etc/haproxy/haproxy.cfg"
    backup: true
  notify:
    - restart_haproxy
  tags: haproxy
...