---
- name: load modules to core
  template:
    src: k8s.conf.j2
    dest: /etc/modules-load.d/k8s.conf


- name: load modules to core
  modprobe:
    name: "{{ item }}"
    state: present
  loop: 
    "{{ core_modules }}"
...