---
- name: Change sysctl
  sysctl: 
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    sysctl_file: /etc/sysctl.d/k8s.conf
    reload: true
  with_items:
      - { name: net.bridge.bridge-nf-call-ip6tables, value: 1 }
      - { name: net.bridge.bridge-nf-call-iptables, value: 1 }
      - { name: net.ipv4.ip_nonlocal_bind, value: 1 }
  become: true

...
